server:
  port: 8585

eureka:
  client:
    service-url:
      defaultZone: http://eureka-sv:8761/eureka/

spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/RomanLepore/configTiendaElec/tree/main
          username: ${GIT_USER}
          password: ${GIT_TOKEN}











